### PR TITLE
Add fabric support

### PR DESCRIPTION
**Pull request by PotatoPresident**
Added a Fabric sub-project for the Fabric Placeholder API
Switched from build script from Maven to Gradle

```json
"chat": "<%luckperms:prefix% ${player} %luckperms:suffix% - %luckperms:context% - %luckperms:highest_group_by_weight% [%luckperms:groups%] - In People: %luckperms:in_group/people% - In aaa: %luckperms:in_group/aaa%> ${message}"
```
image

### CODE REVIEW

**Comment by braunly** [comment]
👍

**Comment by lucko** [comment]
Hi! thanks for this :)

Would you be able to add license headers to the new classes? (just copy and paste from one of the existing classes & make sure there's an empty line beneath)

Happy to merge this once that's done

**Comment by PotatoPresident** [comment]
> Hi! thanks for this :)
> 
> Would you be able to add license headers to the new classes? (just copy and paste from one of the existing classes & make sure there's an empty line beneath)
> 
> Happy to merge this once that's done
> 

Done

**Comment by lucko** [comment]
Thanks for this :)

I've also updated the website so it'll show up there - https://github.com/LuckPerms/LuckPermsWeb/commit/c52f2726ebf8682b62c711d06465b1372d0093b5

**Pull request merged**
