### PR TITLE
Fabric 1.21+ support

### LINKED ISSUE #57: Identifier constructor is private
Since 1.21 the constructors for `net.minecraft.util.Identifier` have been privatised. [(javadoc) ](https://maven.fabricmc.net/docs/yarn-1.21+build.2/net/minecraft/util/Identifier.html#%3Cinit%3E(java.lang.String,java.lang.String))
It should be replaced with `Identifier.of()`. [(javadoc)](https://maven.fabricmc.net/docs/yarn-1.21+build.1/net/minecraft/util/Identifier.html#of(java.lang.String,java.lang.String))

### PR DESCRIPTION
**Pull request by MeiNanziiii**
Adds support for version 1.21 and later while maintaining compatibility with older versions

Fixes #57

### CODE REVIEW

**Comment by acha666** [comment]
Hi, would you mind providing a builded jar file before this PR merged?

I really need a usable version of this mod for 1.21 but don't know how to build it

Thanks

**Comment by Rexwel** [comment]
I support!!!

**Comment by Rexwel** [comment]
> Hi, would you mind providing a builded jar file before this PR merged?
> 
> I really need a usable version of this mod for 1.21 but don't know how to build it
> 
> Thanks

I built this version of the API, but it also crashes the server

**Comment by shvecia** [comment]
> Hi, would you mind providing a builded jar file before this PR merged?
> 
> I really need a usable version of this mod for 1.21 but don't know how to build it
> 
> Thanks

https://drive.google.com/file/d/1VUvjfFis37rGTZ9HO2HQOAG2emVf4hrJ/view?usp=sharing

**Comment by lucko** [comment]
Updated in https://github.com/LuckPerms/placeholders/pull/58 - thanks for the PR!

**Comment by 20NEB09** [comment]
> > Hi, would you mind providing a builded jar file before this PR merged?
> > I really need a usable version of this mod for 1.21 but don't know how to build it
> > Thanks
> 
> https://drive.google.com/file/d/1VUvjfFis37rGTZ9HO2HQOAG2emVf4hrJ/view?usp=sharing

is this a updated version that works on 1.21.7?

**Pull request closed without merging**
